[package]
name = "day10"
version = "0.1.0"
authors = ["Joe Ardent <code@ardent.nebcorp.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
regex = "1.1.0"
tui = "0.3.0"
termion = "1.5.1"
log = "0.4.6"
